Repository thewca/worldcubeassociation.org, pull requests merged in 2019-09, with the labels that each got.

#4615 Update verified translators for Taiwanese
  WcaOnRails/app/controllers/translations_controller.rb
Labels: i18n

#4509 Update the Regulations Translations page.
  .gitignore
  WcaOnRails/app/views/regulations/translations/_index_table.html.erb
  WcaOnRails/app/views/regulations/translations/index.html.erb
  WcaOnRails/config/i18n-tasks.yml.erb
  WcaOnRails/config/locales/en.yml
Labels: wrc-related

#4643 Return WCIF events ordered by rank
  WcaOnRails/app/models/competition.rb
  WcaOnRails/spec/models/competition_wcif_spec.rb
Labels: wcif
